use MP_DOTNET6_API
CREATE TABLE TB_COMPRA(
	ID_COMPRA INT PRIMARY KEY,
	ID_PESSOA INT,
	ID_PRODUTO INT,
	DATACOMPRA DATE,
	CONSTRAINT FK_PESSOA_COMPRA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
	CONSTRAINT FK_PRODUTO_COMPRA FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO)
)
	